services:
  #  admin_react-frontend:
  #    container_name: bikelane-frontend_react-admin
  #    build: ./frontend_admin
  #    ports:
  #      - "5001:5001"
  #    environment:
  #      - CHOKIDAR_USEPOLLING=true
  #    volumes:
  #      - ./frontend_admin:/app
  #      - /app/node_modules
  #    restart: unless-stopped

  #  user_react-frontend:
  #    container_name: bikelane-frontend_react-user
  #    build: ./frontend_user
  #    ports:
  #      - "5003:5003"
  #    environment:
  #      - CHOKIDAR_USEPOLLING=true
  #    volumes:
  #      - ./frontend_user:/app
  #      - /app/node_modules
  #    restart: unless-stopped

  bikelane-backend:
    container_name: bikelane-backend_express
    build: ./backend
    ports:
      - "5002:5002"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: D7Ze0lwV9hMrNQHdz1Q8yi0MIQuOO8
      DB_NAME: bikelane
    depends_on:
      - mysql
    volumes:
      - ./backend:/bikelane-backend
    restart: unless-stopped

  mysql:
    container_name: bikelane-mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: D7Ze0lwV9hMrNQHdz1Q8yi0MIQuOO8
      MYSQL_DATABASE: bikelane
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql-data:
